// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: TEOFlex/Lexico.flex

package com.Lexico.FlexLexico;
import java_cup.runtime.Symbol;
import java_cup.sym;

@SuppressWarnings("fallthrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\1\0\2\1\22\0\1\1\1\2\1\3"+
    "\5\0\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\10\16\1\17\1\20\1\21\1\22"+
    "\1\23\2\0\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\2\25\1\35\1\36\1\37\1\40"+
    "\1\41\1\25\1\42\1\43\1\44\2\25\1\45\3\25"+
    "\1\46\1\0\1\47\1\0\1\50\1\0\1\51\1\52"+
    "\4\51\1\53\1\51\1\54\3\51\1\55\1\51\1\56"+
    "\1\57\2\51\1\60\7\51\1\61\1\0\1\62\123\0"+
    "\1\25\37\0\1\51\u010e\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\2\14\1\15\1\16"+
    "\1\17\1\20\1\21\13\1\1\22\1\23\1\1\1\24"+
    "\1\25\1\26\1\27\1\0\1\30\1\0\1\31\3\0"+
    "\1\32\1\33\1\34\1\35\6\0\1\36\2\0\1\37"+
    "\6\0\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\5\0\1\47\1\50\5\0\1\51\5\0\1\52\6\0"+
    "\1\53\7\0\1\54\1\0\1\55\2\0\1\56\1\57"+
    "\1\2\6\0\1\60\2\0\1\57\15\0\3\57\3\0"+
    "\1\2\1\61\4\0\3\57\1\0\1\2\17\0\1\2"+
    "\14\0\1\62\2\0\1\63\4\0\1\64\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[191];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\63\0\63\0\377"+
    "\0\63\0\63\0\63\0\u0132\0\u0165\0\u0198\0\u01cb\0\u01fe"+
    "\0\63\0\u0231\0\u0264\0\u0297\0\u02ca\0\u02fd\0\u0330\0\u0363"+
    "\0\u0396\0\u03c9\0\u03fc\0\u042f\0\u0462\0\u0495\0\u04c8\0\63"+
    "\0\63\0\u04fb\0\u052e\0\63\0\63\0\63\0\314\0\63"+
    "\0\u0561\0\u0132\0\u0594\0\u05c7\0\u05fa\0\63\0\63\0\63"+
    "\0\63\0\u062d\0\u0660\0\u0693\0\u06c6\0\u06f9\0\u072c\0\63"+
    "\0\u075f\0\u0792\0\63\0\u07c5\0\u07f8\0\u082b\0\u085e\0\u0891"+
    "\0\u08c4\0\u08f7\0\u092a\0\63\0\u095d\0\u05c7\0\63\0\63"+
    "\0\u0990\0\u09c3\0\u09f6\0\u0a29\0\u0a5c\0\63\0\63\0\u0a8f"+
    "\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b\0\u08c4\0\u095d\0\u0b8e\0\u0bc1"+
    "\0\u0bf4\0\u0c27\0\63\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26"+
    "\0\u0d59\0\63\0\u0d8c\0\u0dbf\0\u0df2\0\u0e25\0\u0e58\0\u0e8b"+
    "\0\u0ebe\0\63\0\u0ef1\0\63\0\u0f24\0\u0f57\0\63\0\u0f8a"+
    "\0\u0fbd\0\u0ff0\0\u1023\0\u1056\0\u1089\0\u10bc\0\u10ef\0\63"+
    "\0\u1122\0\u1155\0\u1188\0\u11bb\0\u11ee\0\u0fbd\0\u1221\0\u1254"+
    "\0\u1287\0\u12ba\0\u12ed\0\u1320\0\u1353\0\u1386\0\u13b9\0\u13ec"+
    "\0\u141f\0\u1452\0\u1485\0\u14b8\0\u14eb\0\u151e\0\u11ee\0\63"+
    "\0\u1551\0\u1584\0\u15b7\0\u15ea\0\u161d\0\u1650\0\u1683\0\u16b6"+
    "\0\u16e9\0\u171c\0\u174f\0\u1782\0\u17b5\0\u16e9\0\u17e8\0\u181b"+
    "\0\u184e\0\u1881\0\u18b4\0\u18e7\0\u191a\0\u194d\0\u1980\0\u19b3"+
    "\0\63\0\u19e6\0\u1a19\0\u1a4c\0\u1a7f\0\u1ab2\0\u1ae5\0\u1b18"+
    "\0\u1b4b\0\u1b7e\0\u1bb1\0\u1be4\0\u1c17\0\63\0\u1c4a\0\u1c7d"+
    "\0\63\0\u1cb0\0\u1ce3\0\u1d16\0\u1d49\0\63\0\63";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[191];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\2\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\2\2\1\26\1\27\1\30"+
    "\2\2\1\31\2\2\1\32\1\33\1\34\1\2\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\10\43\1\44\1\45"+
    "\64\0\1\3\103\0\1\46\40\0\3\47\1\50\57\47"+
    "\13\0\1\51\63\0\3\52\57\0\1\53\61\0\1\52"+
    "\1\0\3\17\33\0\1\54\22\0\1\52\1\0\3\17"+
    "\63\0\1\55\2\0\1\56\62\0\1\57\62\0\1\60"+
    "\62\0\1\61\77\0\1\62\20\0\1\63\32\0\1\64"+
    "\67\0\1\65\1\0\1\66\60\0\1\67\56\0\1\70"+
    "\5\0\1\71\63\0\1\72\64\0\1\73\62\0\1\74"+
    "\64\0\1\75\51\0\1\76\62\0\1\77\6\0\1\100"+
    "\32\0\1\101\1\0\3\102\5\0\22\103\3\0\10\103"+
    "\16\0\3\43\5\0\22\43\2\0\11\43\15\0\1\104"+
    "\55\0\1\105\70\0\2\106\67\0\1\107\67\0\1\110"+
    "\107\0\1\111\34\0\1\112\77\0\1\113\46\0\1\114"+
    "\73\0\1\115\66\0\1\116\62\0\1\117\56\0\1\120"+
    "\64\0\1\121\50\0\1\122\66\0\1\123\62\0\1\124"+
    "\42\0\3\125\56\0\1\125\1\0\3\102\70\0\22\103"+
    "\3\0\10\103\2\0\6\126\1\127\4\126\1\130\47\126"+
    "\53\0\1\131\44\0\1\132\55\0\1\133\61\0\1\134"+
    "\4\0\1\135\4\0\1\136\45\0\1\137\70\0\1\140"+
    "\64\0\1\141\65\0\1\142\60\0\1\143\71\0\1\144"+
    "\16\0\6\126\1\127\4\126\1\145\55\126\1\127\4\126"+
    "\1\146\47\126\26\0\1\147\60\0\1\150\66\0\1\151"+
    "\63\0\1\152\73\0\1\153\64\0\1\154\60\0\1\155"+
    "\57\0\1\156\53\0\1\157\62\0\1\160\32\0\6\126"+
    "\1\127\4\126\1\161\55\126\1\162\4\126\1\146\47\126"+
    "\56\0\1\163\46\0\1\164\46\0\1\165\74\0\1\166"+
    "\46\0\1\167\70\0\1\170\44\0\1\171\33\0\1\172"+
    "\10\173\2\0\6\174\1\175\4\174\1\176\47\174\6\177"+
    "\1\200\4\177\1\201\47\177\55\0\1\202\35\0\1\203"+
    "\67\0\1\204\57\0\1\205\66\0\1\206\76\0\1\207"+
    "\22\0\1\210\1\0\3\211\5\0\22\212\3\0\10\212"+
    "\16\0\3\173\5\0\22\173\2\0\1\213\10\173\2\0"+
    "\13\174\1\214\47\174\6\175\1\215\54\175\6\177\1\200"+
    "\62\177\1\200\4\177\1\216\55\177\1\200\4\177\1\217"+
    "\47\177\57\0\1\220\15\0\1\221\74\0\1\222\100\0"+
    "\1\223\32\0\1\224\64\0\2\225\61\0\3\226\56\0"+
    "\1\226\1\0\3\211\31\0\1\172\10\173\16\0\1\171"+
    "\7\0\22\212\2\0\1\172\10\173\14\0\1\210\1\0"+
    "\3\227\5\0\22\173\2\0\1\213\10\173\2\0\13\174"+
    "\1\176\47\174\6\175\1\215\4\175\1\230\47\175\6\177"+
    "\1\200\4\177\1\231\47\177\43\0\1\232\61\0\1\233"+
    "\44\0\1\234\101\0\1\235\33\0\2\225\32\0\1\172"+
    "\10\173\16\0\3\226\31\0\1\172\10\173\14\0\1\226"+
    "\1\0\3\227\5\0\22\173\2\0\1\213\10\173\2\0"+
    "\6\175\1\215\4\175\1\236\47\175\6\236\1\237\54\236"+
    "\30\0\1\240\62\0\1\241\70\0\1\242\54\0\1\243"+
    "\32\0\6\236\1\237\4\236\1\244\47\236\26\0\1\245"+
    "\46\0\1\246\62\0\1\247\76\0\1\250\34\0\6\236"+
    "\1\237\4\236\1\251\47\236\44\0\1\252\61\0\1\253"+
    "\62\0\1\254\63\0\1\255\52\0\1\256\56\0\1\257"+
    "\62\0\1\260\66\0\1\261\66\0\1\262\50\0\1\263"+
    "\62\0\1\264\74\0\1\265\61\0\1\266\67\0\1\267"+
    "\62\0\1\270\55\0\1\271\57\0\1\272\62\0\1\273"+
    "\66\0\1\274\62\0\1\275\61\0\1\276\62\0\1\277"+
    "\23\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[7548];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\2\11\1\1\3\11\5\1\1\11"+
    "\16\1\2\11\2\1\3\11\1\0\1\11\1\0\1\1"+
    "\3\0\4\11\6\0\1\11\2\0\1\11\6\0\2\1"+
    "\1\11\2\1\2\11\5\0\2\11\5\0\1\1\5\0"+
    "\1\11\6\0\1\11\7\0\1\11\1\0\1\11\2\0"+
    "\1\11\2\1\6\0\1\11\2\0\1\1\15\0\3\1"+
    "\3\0\1\1\1\11\4\0\3\1\1\0\1\1\17\0"+
    "\1\11\14\0\1\11\2\0\1\11\4\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[191];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Symbol(1000, new TokenObject("ERROR", yytext()));
            }
          // fall through
          case 54: break;
          case 2:
            { 
            }
          // fall through
          case 55: break;
          case 3:
            { return new Symbol(18, new TokenObject("Comillas", yytext()));
            }
          // fall through
          case 56: break;
          case 4:
            { return new Symbol(21, new TokenObject("Paréntesis abierto", yytext()));
            }
          // fall through
          case 57: break;
          case 5:
            { return new Symbol(22, new TokenObject("Paréntesis cerrado", yytext()));
            }
          // fall through
          case 58: break;
          case 6:
            { return new Symbol(42, new TokenObject("Multiplicación", yytext()));
            }
          // fall through
          case 59: break;
          case 7:
            { return new Symbol(40, new TokenObject("Suma", yytext()));
            }
          // fall through
          case 60: break;
          case 8:
            { return new Symbol(38, new TokenObject("Coma", yytext()));
            }
          // fall through
          case 61: break;
          case 9:
            { return new Symbol(41, new TokenObject("Resta", yytext()));
            }
          // fall through
          case 62: break;
          case 10:
            { return new Symbol(39, new TokenObject("Punto", yytext()));
            }
          // fall through
          case 63: break;
          case 11:
            { return new Symbol(43, new TokenObject("División", yytext()));
            }
          // fall through
          case 64: break;
          case 12:
            { return new Symbol(47, new TokenObject("NUM_INT_VALOR", yytext()));
            }
          // fall through
          case 65: break;
          case 13:
            { return new Symbol(37, new TokenObject("Dos puntos", yytext()));
            }
          // fall through
          case 66: break;
          case 14:
            { return new Symbol(36, new TokenObject("Punto y coma", yytext()));
            }
          // fall through
          case 67: break;
          case 15:
            { return new Symbol(29, new TokenObject("Menor que", yytext()));
            }
          // fall through
          case 68: break;
          case 16:
            { return new Symbol(26, new TokenObject("Asignación simple", yytext()));
            }
          // fall through
          case 69: break;
          case 17:
            { return new Symbol(30, new TokenObject("Mayor que", yytext()));
            }
          // fall through
          case 70: break;
          case 18:
            { return new Symbol(23, new TokenObject("Corchetes abierto", yytext()));
            }
          // fall through
          case 71: break;
          case 19:
            { return new Symbol(24, new TokenObject("Corchetes cerrado", yytext()));
            }
          // fall through
          case 72: break;
          case 20:
            { return new Symbol(44, new TokenObject("ID", yytext()));
            }
          // fall through
          case 73: break;
          case 21:
            { return new Symbol(19, new TokenObject("Llave abierta", yytext()));
            }
          // fall through
          case 74: break;
          case 22:
            { return new Symbol(20, new TokenObject("Llave cerrada", yytext()));
            }
          // fall through
          case 75: break;
          case 23:
            { return new Symbol(34, new TokenObject("Diferente", yytext()));
            }
          // fall through
          case 76: break;
          case 24:
            { return new Symbol(45, new TokenObject("STRING_VALOR", yytext()));
            }
          // fall through
          case 77: break;
          case 25:
            { return new Symbol(46, new TokenObject("NUM_REAL_VALOR", yytext()));
            }
          // fall through
          case 78: break;
          case 26:
            { return new Symbol(35, new TokenObject("Asignación múltiple", yytext()));
            }
          // fall through
          case 79: break;
          case 27:
            { return new Symbol(32, new TokenObject("Menor o igual", yytext()));
            }
          // fall through
          case 80: break;
          case 28:
            { return new Symbol(33, new TokenObject("Igual", yytext()));
            }
          // fall through
          case 81: break;
          case 29:
            { return new Symbol(31, new TokenObject("Mayor o igual", yytext()));
            }
          // fall through
          case 82: break;
          case 30:
            { return new Symbol(2, new TokenObject("IF", yytext()));
            }
          // fall through
          case 83: break;
          case 31:
            { return new Symbol(9, new TokenObject("OR", yytext()));
            }
          // fall through
          case 84: break;
          case 32:
            { return new Symbol(50, new TokenObject("CTE_E", yytext()));
            }
          // fall through
          case 85: break;
          case 33:
            { return new Symbol(48, new TokenObject("CTE_STR", yytext()));
            }
          // fall through
          case 86: break;
          case 34:
            { return new Symbol(28, new TokenObject("Cierra bloque comentario", yytext()));
            }
          // fall through
          case 87: break;
          case 35:
            { return new Symbol(27, new TokenObject("Abre bloque comentario", yytext()));
            }
          // fall through
          case 88: break;
          case 36:
            { return new Symbol(51, new TokenObject("CTE_B", yytext()));
            }
          // fall through
          case 89: break;
          case 37:
            { return new Symbol(25, new TokenObject("Asignación", yytext()));
            }
          // fall through
          case 90: break;
          case 38:
            { return new Symbol(8, new TokenObject("AND", yytext()));
            }
          // fall through
          case 91: break;
          case 39:
            { return new Symbol(16, new TokenObject("INT", yytext()));
            }
          // fall through
          case 92: break;
          case 40:
            { return new Symbol(7, new TokenObject("NOT", yytext()));
            }
          // fall through
          case 93: break;
          case 41:
            { return new Symbol(49, new TokenObject("CTE_F", yytext()));
            }
          // fall through
          case 94: break;
          case 42:
            { return new Symbol(4, new TokenObject("ELSE", yytext()));
            }
          // fall through
          case 95: break;
          case 43:
            { return new Symbol(3, new TokenObject("THEN", yytext()));
            }
          // fall through
          case 96: break;
          case 44:
            { return new Symbol(5, new TokenObject("ENDIF", yytext()));
            }
          // fall through
          case 97: break;
          case 45:
            { return new Symbol(15, new TokenObject("FLOAT", yytext()));
            }
          // fall through
          case 98: break;
          case 46:
            { return new Symbol(1, new TokenObject("WHILE", yytext()));
            }
          // fall through
          case 99: break;
          case 47:
            { return new Symbol(52, new TokenObject("WRITE", yytext()));
            }
          // fall through
          case 100: break;
          case 48:
            { return new Symbol(17, new TokenObject("STRING", yytext()));
            }
          // fall through
          case 101: break;
          case 49:
            { return new Symbol(14, new TokenObject("AsigComp", yytext()));
            }
          // fall through
          case 102: break;
          case 50:
            { return new Symbol(10, new TokenObject("DECLARE.SECTION", yytext()));
            }
          // fall through
          case 103: break;
          case 51:
            { return new Symbol(12, new TokenObject("PROGRAM.SECTION", yytext()));
            }
          // fall through
          case 104: break;
          case 52:
            { return new Symbol(11, new TokenObject("ENDDECLARE.SECTION", yytext()));
            }
          // fall through
          case 105: break;
          case 53:
            { return new Symbol(13, new TokenObject("ENDPROGRAM.SECTION", yytext()));
            }
          // fall through
          case 106: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
