
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 24 01:19:03 ART 2024
//----------------------------------------------------

package com.Lexico.FlexLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 9;
  public static final int Punto_y_coma = 32;
  public static final int Coma = 34;
  public static final int If = 3;
  public static final int Id = 44;
  public static final int Parentesis_cerrado = 21;
  public static final int Diferente = 30;
  public static final int Endprogram_section = 13;
  public static final int Else = 5;
  public static final int Llave_abierta = 18;
  public static final int Asignacion = 24;
  public static final int Then = 4;
  public static final int Enddeclare_section = 11;
  public static final int Endif = 6;
  public static final int Cte_s = 39;
  public static final int While = 2;
  public static final int Division = 38;
  public static final int Mayor_o_igual_que = 27;
  public static final int Int = 16;
  public static final int Float = 15;
  public static final int Corchete_cerrado = 23;
  public static final int Mayor_que = 26;
  public static final int Asign_mult = 31;
  public static final int EOF = 0;
  public static final int Cte_f = 40;
  public static final int Cte_e = 41;
  public static final int Not = 7;
  public static final int And = 8;
  public static final int error = 1;
  public static final int Cte_b = 42;
  public static final int Menor_o_igual_que = 28;
  public static final int Parentesis_abierto = 20;
  public static final int Program_section = 12;
  public static final int Dos_puntos = 33;
  public static final int Declare_section = 10;
  public static final int String = 17;
  public static final int Menor_que = 25;
  public static final int Asign_comp = 14;
  public static final int Resta = 36;
  public static final int Corchete_abierto = 22;
  public static final int Llave_cerrada = 19;
  public static final int Multiplicacion = 37;
  public static final int Write = 43;
  public static final int Suma = 35;
  public static final int Igual = 29;
}

